services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    working_dir: /code/server
    volumes:
      - .:/code
      - static-data:/code/server/static
      - media-data:/code/server/media
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/code/server
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-data:/code/server/static
      - media-data:/code/server/media
    restart: unless-stopped

volumes:
  db-data:
  static-data:
  media-data:
